collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      

include:
  - assets/videos/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#repository: indracosimo/indracosimo.github.io
